site_name: "Copier Modern Python"
site_description: "Copier template for Python projects managed by PDM and Nox."
site_url: "https://georgedouzas.github.io/copier-modern-python"
repo_url: "https://github.com/georgedouzas/copier-modern-python"
repo_name: "georgedouzas/copier-modern-python"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md]

theme:
  name: material
  features:
  - content.code.annotate
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
    primary: blue

nav:
  - index.md
  - Overview:
    - Changelog: overview/changelog.md
    - License: overview/license.md
  - Development:
    - Contributing: development/contributing.md
    - Code of Conduct: development/code_of_conduct.md

extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- mdx_truly_sane_lists

plugins:
- section-index
- search
- markdown-exec

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/georgedouzas
